# Generated by Django 3.1.6 on 2021-02-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioaplicacion',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='usuarioaplicacion',
            name='aplicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.aplicacion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usuarioaplicacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuarioaplicacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
