# Generated by Django 3.1.6 on 2021-02-04 19:44

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_solicitudusuario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudusuario',
            name='clave',
            field=fernet_fields.fields.EncryptedCharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
