# Generated by Django 3.1.6 on 2021-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210203_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudusuario',
            name='clave',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudusuario',
            name='login',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
